version: '3'
services:
  # MongoDB service
  mongo:
    image: mongo:6.0.1
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  # Node.js/Hapi.js API service
  api:
    build: .
    container_name: node-sweat
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm run dev # Use nodemon during development
    env_file:
      - .env  # Use the .env file for environment variables
    depends_on:
      - mongo
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
